apiVersion: v1
kind: Secret
metadata:
  name: artbackend-postgres-secret
  namespace: sistema #
  labels:
  app: Artlif #
type: Opaque
data:
  DB_USER: LiuoZ_G4vHI7ODP1eG8r9w
  DB_PASSAWORD: LiuoZ_G4vHI7ODP1eG8r9w
  DB_NAME: LiuoZ_G4vHI7ODP1eG8r9w
  